# 01 Brief review of Python

Part of ["Introduction to Data Science" course](https://github.com/kupav/data-sc-intro) by Pavel Kuptsov, [kupav@mail.ru](mailto:kupav@mail.ru)

Recommended reading for this section:

1. Ben Stephenson. "The Python Workbook. A brief introduction with exercises and solutions", Springer, 2019.

## Lesson 1

### Hello world

Standard first step in learning of any language: program "Hello world". 

It is pretty short in Python

In [46]:
print("Hello, world!")

Hello, world!


Each `print` by default ends line, 

In [1]:
print("Hello,")
print("world!")

Hello,
world!


To change it, one can do as follows

In [3]:
print("Hello,", end="_")
print("world!")

Hello,_world!


One can print several elements

In [6]:
print("Hello", ", ", "world", "!")

Hello ,  world !


By default, elements are separated by space `" "`. To change it:

In [7]:
print("Hello", ", ", "world", "!", sep="")

Hello, world!


### Comments

Symbol `#` means a comment. Everything to the right will be ignored by Python.

The following code does nothing

In [47]:
# print("Hello, world!")

### Variables

A variable is a named location in a computer memory that holds a value.

Variable names in Python: letters, numbers and underscores. Name cannot begin with a number. Letters are case sensitive.

Correct variable names:

```python
step_size
StepSize
stepSize
size21
step1_size5
```

Incorrect names:

```python
step size # no spaces inside are allowed
1_step # no numbers in the beginning
featur%one # symbol % is not allowed
```

Variables are created using assignment statement: the name appears to the left of `=` the value that will be stored in the variable appears to the right of it.

To see what is stored in a variable we use `print()`.

In [48]:
s = "one, two, three"
a = 4
print(s, a)

one, two, three 4


A variable can contain a special value `None`. It means "no value is held in this variable 
but it exists yet".

In [49]:
x = None
print(x)

None


### Expressions and math operators

The right hand side of the assignment statement can be an expression: It can have numbers, and standard math operators like (`+`), (`-`), (`/`), (`*`). 

It also can include variables.

Not obvious operators: exponentiation (`**`), floor division (`//`), module (`%`).

In [50]:
x = 1
y = x + 1
z = y ** 3
print("x=", x, "y=", y, "z=", z)

x= 1 y= 2 z= 8


Figure out how operator (`//`) and (`%`) work

In [51]:
x = 14
y = 5
d = x / y
print("d=", d)

d= 2.8


Operator (`//`) computes the floor of the quotient that results when one number is divided by another. 

In [52]:
f = x // y
print("f=", f)

f= 2


Operator (`%`) computes the remainder when one number is divided by another.

In [53]:
r = x % y
print("r=", r)

r= 4


Check.

In [54]:
x1 = y * f + r
print("x=", x, "x1=", x1)

x= 14 x1= 14


The same variable can appear on both sides.

In [55]:
x = 15
x = x + 2
print(x)

17


There is a convenient compact form for it `x += 2`. Works with all math operators.

In [56]:
x = 15
print(x)
x += 2
print(x)
x *= 3
print(x)

15
17
51


### Calling functions 

Parts of code can be wrapped into functions.

- to avoid retyping
- to increase clarity

An example: let us make a rounding of a real number. We can use floor division (`//`) 
for it. 

Let us see what happen when we divide by 1:

In [1]:
print(15.2 // 1)
print(15.4 // 1)
print(15.6 // 1)
print(15.8 // 1)

15.0
15.0
15.0
15.0


But we want `15.6 -> 16`. Just add `0.5` before division.

In [58]:
x = 15.4
rx = (x + 0.5) // 1
print(rx)

15.0


In [59]:
x = 15.6
rx = (x + 0.5) // 1
print(rx)

16.0


It works good. But we don't want to retype it again and again. A function will help. 

We could write a function for our rounding procedure, but Python already has one: `round()`

In [60]:
x = 15.4
print(round(x))

15


In [61]:
x = 15.6
print(round(x))

16


By the way: `print()` is also a function.

Notice: when we call a function we write its name followed by its parameters in parenthesis.

Also notice a bit different results: our rounding expression returns numbers with the decimal point, `15.0`, `16.0`, while function `round` gives `15`, `16`. This is because `round` additionally performs a type conversion: from real `15.0` to integer `15`.

### Types

Content of a variable always has type. Simple standard types:

- `int` - integer number, no decimal point (`12`, `-2312`)
- `float` - real number, decimal point or `e`-symbol is used (`.321`, `12.0`, `34.591`, `1.28e-11`, `1e13`)
- `complex` - complex number, includes imaginary unit (`3j`, `12.3+3.2j`) 
- `str` - text string, enclosed in quotation marks or apostrophes (`"one and two"`, `'Data'`)
- `bool` - boolean value, can be either `True` or `False`

Why there are many types? Because different types are processed in different ways. 

Types can be converted. Just use type as a function name

In [62]:
x = 15.6
rx = (x + 0.5) // 1
irx = int(rx)  # converts here float variable rx to int type
print("rx=", rx, "irx=", irx)

rx= 16.0 irx= 16


In [63]:
x = 953.3
s = "x=" + str(x)  # here x is converted to string and concatenated with 'x='
print(s)

x=953.3


Types can be checked using function `type()`

In [64]:
i = 2
print(type(i))

<class 'int'>


In [65]:
x = 2.3
print(type(x))

<class 'float'>


In [66]:
c = 3.4 + 5.6j
print(type(c))

<class 'complex'>


In [67]:
s = "expansion"
print(type(s))

<class 'str'>


### Working with strings

Operation on strings

- computing length of a string
- concatenating two strings
- taking substrings and individual symbols

Length is computed with function `len()`

In [68]:
s1 = "Data"
string_length = len(s1)
print(string_length)

4


Concatenation of strings is done with (`+`)

In [69]:
s1 = "this is string"
s2 = s1 + " and " + s1
print(s2)

this is string and this is string


Taking symbols and substrings: Key idea is that symbols are enumerated starting from zero:
```
   01234567
s="compound"
```
Elements are accessed by index:
```
s[0] -> c
s[1] -> o
s[2] -> m
s[3] -> p
...
```
Substrings are accessed via ranges of index
```
s[0:3] -> 'com'
s[:3]  -> 'com'
s[3:8] -> 'pound'
s[-3:] -> 'und'
```

In [70]:
# Symbol positions start from 0
#     012345678901234"  
s1 = "this is string!"
print(s1)
w1 = s1[0:4]
w2 = s1[5:7]
w3 = s1[-7:-1]
s2 = w2 + " " + w1 + " " + w3 + "?"
print(s2)

this is string!
is this string?


Number can be appear in a string:
```python
s = "value of N is 999"
```
Or can be written as a string
```python
a = "1.234"
```
To use it in computations one have to convert it to a numerical type, `int` or `float`.

In [71]:
s = "value of N is 999"
N = s[-3:]
print(N)
print(type(N))  # N is a string, not a number

999
<class 'str'>


In [72]:
N1 = N + 1  # Error, types are incompatible

TypeError: can only concatenate str (not "int") to str

In [73]:
N = int(s[-3:])  # Convert string '999' to number 999
print(N)
print(type(N))

999
<class 'int'>


In [74]:
N1 = N + 1  # Now N can appear in computations
print(N1)

1000


In [75]:
a = "1.234"
b = a + 1.766  # Error because types are incompatible

TypeError: can only concatenate str (not "float") to str

In [76]:
b = float(a) + 1.766  # Now wlikeorks
print(b)

3.0


### String formatting

Concatenation is often not enough to represent information appropriately. Complicated cases are processed via string formating: curly brackets and `.format()`

In [78]:
x = 10.0 / 7.0
y = 13.0 / 7.0
s = 'Results: x={} and y={}'.format(x, y)
print(s)

Results: x=1.4285714285714286 and y=1.8571428571428572


Printed values can be rounded (but actual variable values are unchanged)
```python
'{:with.precision}'.format(x)
```
Here `with` is total with, and `precision` is precision.

In [79]:
x = 10.0 / 7.0
y = 13.0 / 7.0
s = 'Results: x={:4.3} and y={:5.4}'.format(x, y)
print(s)

Results: x=1.43 and y=1.857


f-strings is more convenient way of formating. One puts `f`-symbol before the string and write variables inside curly brackets.

In [80]:
x = 10.0 / 7.0
y = 13.0 / 7.0
s = f'Results: x={x:4.3} and y={y:5.4}'
print(s)

Results: x=1.43 and y=1.857


### Reading input

Program can read input from the keyboard by calling the `input()` function. Data are obtained as strings. The programmer must convert it to the proper type.

If called with a string argument like this: `input('Enter a value')` a hint message is printed.

In [81]:
s = input("Input i")
print(type(s))

Input i6
<class 'str'>


In [82]:
i = int(s)
print(i + 15)

21


Keyboard input is typically not used in data science. Data are usually read from files.

### Modules

Some functions are available in Python anytime and anywhere: `print()`, `input()`, `round()`

Less common functions are collected in modules. Before using they have to be imported to the program using command `import`

Math functions live in module `math`. Its import is done with the command
```python
import math
```
Using module content: add prefix `math.` before function name:
```python
a = math.sin(0.1)
```

In [83]:
import math

x = (math.sqrt(5) + 1) / 2
print(x)

1.618033988749895


If a module name is too long one can rename it when importing

In [84]:
import datetime as dt

today = dt.date.today()
print("Today's date:", today)

Today's date: 2020-10-21


Or one can merge a module content to the global name space - no reference to the module name will be required

In [85]:
from random import *

print(randint(1, 10))

8


Sometimes only one function is needed. Then we import exactly what we want

In [86]:
from math import log10

print(log10(10**5))

5.0


### Module numpy

Standard module `math` is usually not used in data science. It is not enough for really serious math computations. 

In fact the standard for serious work is `numpy` module. It contains all functions from `math` and much much more.

In [87]:
import numpy as np  # this is standard form of import

x = np.sin(np.pi / 2)**2 + np.cos(np.pi / 2)**2
print(x)

1.0


Notice that `math` is a part of Python and is always available. Module `numpy` must be installed separately. 

### Exercises

All exercises in this section are taken from book \[1\]

1\. In many jurisdictions a small deposit is added to drink containers to encourage people to recycle them. In one particular jurisdiction, drink containers holding one liter or less have a \\$0.10 deposit, and drink containers holding more than one liter have a \\$0.25 deposit. Write a program that reads the number of containers of each size from the user. Your program should continue by computing and displaying the refund that will be received for returning those containers. Format the output so that it includes a dollar sign and two digits to the right of the decimal point.

2\. The program that you create for this exercise will begin by reading the cost of a meal ordered at a restaurant from the user. Then your program will compute the tax and tip for the meal. Use your local tax rate when computing the amount of tax owing. Compute the tip as 18 percent of the meal amount (without the tax). The output from your program should include the tax amount, the tip amount, and the grand total for the meal including both the tax and the tip. Format the output so that all of the values are displayed using two decimal places.

3\. Write a program that reads a positive integer, n, from the user and then displays the sum of all of the integers from 1 to n. The sum of the first n positive integers can be

$$S = \frac{n(n+1)}{2}$$

4\. Pretend that you have just opened a new savings account that earns 4 percent interest per year. The interest that you earn is paid at the end of the year, and is added to the balance of the savings account. Write a program that begins by reading the amount of money deposited into the account from the user. Then your program should compute and display the amount in the savings account after 1, 2, and 3 years. Display each amount so that it is rounded to 2 decimal places. 

5\. In the United States, fuel efficiency for vehicles is normally expressed in miles-per-gallon (MPG). In Canada, fuel efficiency is normally expressed in liters-per-hundred kilometers (L/100km). Use your research skills to determine how to convert from MPG to L/100km.Then create a program that reads a value from the user in American units and displays the equivalent fuel efficiency in Canadian units.

6\. The surface of the Earth is curved, and the distance between degrees of longitude
varies with latitude. As a result, finding the distance between two points on the surface
of the Earth is more complicated than simply using the Pythagorean theorem.

Let ($t_1$, $g_1$) and ($t_2$ , $g_2$) be the latitude and longitude of two points on the Earth’s surface. The distance between these points, following the surface of the Earth, in
kilometers is:

$$
D = 6371.01 \arccos(\sin t_1 \sin t_2 + \cos t_1 \cos t_2 \cos(g_1-g_2))
$$

*The value 6371.01 in the previous equation wasn’t selected at random. It is the
average radius of the Earth in kilometers.*

Create a program that allows the user to enter the latitude and longitude of two
points on the Earth in degrees. Your program should display the distance between
the points, following the surface of the earth, in kilometers.

*Hint: Python’s trigonometric functions operate in radians. As a result, you will
need to convert the user’s input from degrees to radians before computing the
distance with the formula discussed previously. The `math` module as well as `numpy` 
contains a function named radians which converts from degrees to radians.*

7\. Many people think about their height in feet and inches, even in some countries that
primarily use the metric system. Write a program that reads a number of feet from
the user, followed by a number of inches. Once these values are read, your program
should compute and display the equivalent number of centimeters.

*Hint: One foot is 12 inches. One inch is 2.54 centimeters.*

8\. Write a program that begins by reading a radius, $r$, from the user. The program will
continue by computing and displaying the area of a circle with radius $r$ and the
volume of a sphere with radius $r$. Use the pi constant in the `math` or `numpy` modules in your calculations. Use Internet to look up the necessary formula if you don't have them memorized.

9\. Python’s `time` module includes several time-related functions. One of these is the
`asctime` function which reads the current time from the computer’s internal clock
and returns it in a human-readable format. Use this function to write a program that
displays the current time and date. Your program will not require any input from the
user.

10\. When the wind blows in cold weather, the air feels even colder than it actually is
because the movement of the air increases the rate of cooling for warm objects, like
people. This effect is known as wind chill.

In 2001, Canada, the United Kingdom and the United States adopted the following formula for computing the wind chill index. Within the formula $T_a$ is the air temperature in degrees Celsius and $V$ is the wind speed in kilometers per hour. A similar formula with different constant values can be used for temperatures in degrees Fahrenheit and wind speeds in miles per hour.

$$
WCI = 13.12 + 0.6215 T_a − 11.37 V^{0.16} + 0.3965 T_a V^{0.16}
$$

Write a program that begins by reading the air temperature and wind speed from the
user. Once these values have been read your program should display the wind chill
index rounded to the closest integer.

_The wind chill index is only considered valid for temperatures less than or
equal to 10 degrees Celsius and wind speeds exceeding 4.8 kilometers per
hour._

11\. Develop a program that reads a four-digit integer from the user and displays the sum
of its digits. For example, if the user enters `3141` then your program should display
`3 + 1 + 4 + 1 = 9`.

12\. Create a program that reads three integers from the user and displays them in sorted
order (from smallest to largest). Use the `min` and `max` functions to find the smallest
and largest values. The middle value can be found by computing the sum of all three
values, and then subtracting the minimum value and the maximum value.

13\. A bakery sells loaves of bread for \$3.49 each. Day old bread is discounted by 60
percent. Write a program that begins by reading the number of loaves of day old
bread being purchased from the user. Then your program should display the regular
price for the bread, the discount because it is a day old, and the total price. Each of
these amounts should be displayed on its own line with an appropriate label. All of
the values should be displayed using two decimal places, and the decimal points in
all of the numbers should be aligned when reasonable values are entered by the user.

## Lesson 2

### Conditional constructs

Conditional constructs allows branching: statements may or may not be executed depending on some conditions.

Forms of conditional constructs:
- if
- if-else
- if-elif-else
- if-elif

Remark for those who is familiar with other languages: Python does not have select-case statements. Their are simulated via if-elif-else constructs.

### If statements

The simplest form consists of `if` statement only:
```python
if <condition_is_true>:
    <do_something>
<continue_working>
```
Observe colon `:` ending the line of `if` statement. It must be there according to the language rules.

Statements `<do_something>` are executed only if the result of the condition evaluation is `True`. Otherwise this construct does nothing. Statement `<continue_working>` are executed in any case.

The body of an `if` statement consists of one or more statements that must be **indented more than the `if` keyword**. 

The body ends before the next line that is indented **the
same amount as (or less than) the `if` keyword**. 

Programmers can choose how many spaces to use when indenting the bodies of `if` and other similar statements. Recommended value is 4 spaces. 

Often the condition is written as a relation:
```python
x < y
x > y
x <= y
x >= y
x == y
x != y
x is None
x is not None
```

In [92]:
N = int(input("Enter N="))
if N > 0:
    print("You have entered a positive value")
if N <= 0:
    print("You have entered a negative value or zero")

Enter N=7
You have entered a positive value


### If-else statements

In the previous example the second test is redundant. If the condition `N > 0` is false, `N <= 0` is true automatically. Two calls of `print()` are mutually exclusive.

Instead of the second `if` it is better to use if-else statement 
```python
if <condition_is_true>:
    <do_something>
else:
    <do_other_things>
<continue_working>
```
Observe colons `:` ending both `if` and `else` lines. They must be there.

Observe the same indentations of `if` and `else` bodies.

Either `<do_something>` or `<do_other_things>` will be executed. Never both of them!

To fix the previous example we substitute the second `if` with `else` statement.

In [91]:
N = int(input("Enter N="))
if N > 0:
    print("You have entered a positive value")
else:
    print("You have entered a negative value or zero")

Enter N=6
You have entered a positive value


### If-elif-else statements

If there are more then two options:
```python
if <condition_1_is_true>:
    <do_something_1>
elif <condition_2_is_true>:
    <do_something_2>
elif <condition_3_is_true>:
    <do_something_3>
else:
    <do_other_things>
<continue_working>
```

Exactly one statement will be executed: either `<do_something_1>` or `<do_something_2>` or `<do_something_3>` or `<do_other_things>`.

Branch `else` can be omitted. In this case if non of the conditions is true if-elif block does nothing.

In [96]:
N = int(input("Enter N="))
if N > 0:
    print("You have entered a positive value")
elif N == 0:
    print("You have entered zero")
else:
    print("You have entered a negative value")

Enter N=-1
You have entered a negative value


### Nested if


The body of if-elif-else block can contain almost any Python statements, including another if blocks. 

In [16]:
x = float(input("Enter x="))

if x < 0.0:
    descr = "negative"
elif x == 0.0:
    descr = "zero"
else:
    descr = "positive"
    if x < 1.0:
        descr = "small " + descr
    if x >= 10:
        descr = "big " + descr
print(f"You have eneterd a {descr} value")

Enter x=222
You have eneterd a big positive value


### Boolean logic

Results of relations can be modified and they can be combined using logical operators `not`, `and`, `or`.

Operator `not` switches a logical value. The truth table:

| x | not x |
| :-: | :-: |
| False | True |
| True | False|

Operator `and` compares two boolean values. The result is true only when both arguments are true. The truth table:

| x | y | x and y |
| :-: | :-: | :-: |
| False | False | False |
| False | True | False |
| True | False | False |
| True | True | True |

Operator `or` also compares two boolean values. The result is false only when both arguments are false. The truth table:

| x | y | x or y |
| :-: | :-: | :-: |
| False | False | False |
| False | True | True |
| True | False | True |
| True | True | True |


In [4]:
N = int(input('Enter N='))

if N == 2 or N == 4 or N == 6 or N == 8 or N == 10:
    print("You have entered an even number")
elif N >= 1 and N <= 9:
    print("You have entered an odd number")
else:
    print("Have no idea what you have entered")

Enter N=0
Have no idea what is entered


### While loops

A `while` loop repeatedly executes its body statements as long as a condition evaluates to `True`.
```python
while <condition_is_true>:
    <do_something_again_and_again>
```

The body of the loop must be **indented more than the `while` keyword**. 

The body ends before the next line that is indented **the
same amount as (or less than) the `while` keyword**. 


In [40]:
N = int(input("Enter dividend N="))
K = int(input("Enter divisor  K="))

sum = 0
quotient = 0
remainder = 0
print()
while sum < N:
    sum += K
    quotient += 1
    print(f"watching: sum={sum:4}, quotient={quotient:4}, (sum<N)={sum<N}")

print()
if sum > N:
    quotient -= 1
    
remainder = N - quotient * K
    
print(f"Result: {N} = {K} * {quotient} + {remainder}")    

Enter dividend N=45
Enter divisor  K=4

watching: sum=   4, quotient=   1, (sum<N)=True
watching: sum=   8, quotient=   2, (sum<N)=True
watching: sum=  12, quotient=   3, (sum<N)=True
watching: sum=  16, quotient=   4, (sum<N)=True
watching: sum=  20, quotient=   5, (sum<N)=True
watching: sum=  24, quotient=   6, (sum<N)=True
watching: sum=  28, quotient=   7, (sum<N)=True
watching: sum=  32, quotient=   8, (sum<N)=True
watching: sum=  36, quotient=   9, (sum<N)=True
watching: sum=  40, quotient=  10, (sum<N)=True
watching: sum=  44, quotient=  11, (sum<N)=True
watching: sum=  48, quotient=  12, (sum<N)=False

Result: 45 = 4 * 11 + 1


### For loops

Loop `for` also repeats the execution of its body and do it for each element of a collection:
```python
for <variable> in <collection>:
    <do_something_for_each_element_in_collection>
```

Observe the indentation. Rules are the same as for `if` and `while`.

The collection can be a range of integers, the letters in a string and some others.

Each element in the collection is copied into `<variable>` before each execution of the body.

A collection of integers can be constructed by calling function `range()`.

In [44]:
for i in range(5):  # i = [0, 1, 2, 3, 4]
    print(f"i={i}, i squared={i**2}")

i=0, squared i=0
i=1, squared i=1
i=2, squared i=4
i=3, squared i=9
i=4, squared i=16


In [45]:
for i in range(5, 10):  # i = [5, 6, 7, 8, 9]
    print(f"i={i}, i squared={i**2}")

i=5, i squared=25
i=6, i squared=36
i=7, i squared=49
i=8, i squared=64
i=9, i squared=81


In [56]:
for i in range(1, 11, 2):  # i = [1, 3, 5, 7, 9]
    print(f"i={i}, i squared={i**2}")

i=1, i squared=1
i=3, i squared=9
i=5, i squared=25
i=7, i squared=49
i=9, i squared=81


In [52]:
for i in range(10, 0, -2):  # i = [10, 8, 6, 4, 2]
    print(f"i={i}, i squared={i**2}")

i=10, i squared=100
i=8, i squared=64
i=6, i squared=36
i=4, i squared=16
i=2, i squared=4


Observe that range by default starts from zero. Last range number is ignored.

### Nested loops

Body of a loop can contain `if` statements as well as another loops. 

In [59]:
s = input("Enter a word (blank to quit)")

while s != "":
    for i in range(3):
        print(f"{s} ", end="")  # do not go to new line
    print()  # now go to new line when for-loop is finished
    
    s = input("Enter a word (blank to quit)")

Enter a word (blank to quit)read
read read read 
Enter a word (blank to quit)work
work work work 
Enter a word (blank to quit)


### Break and continue

Previous code was not so good. We were forced to write two identical input statements. This is because the conditions is checked before execution the body. 

Some other programming languages have do-while loops where the condition is checked after the execution. But Python does have it.

But we can simulate do-while loop using is-statement and `break`.

Operator `break` immediately breaks loop repetitions. Works both with `for` and `while` loops.

In [67]:
sum = 0
while True:
    N = int(input("Enter N="))
    sum += N
    print(f"sum={sum}")
    if sum > 10:
        break

Enter N=8
sum=8
Enter N=8
sum=16


Operator `continue` stops current execution and jump to another loop repetition. Works both with `for` and `while` loops.

In [69]:
sum = 0
while True:
    N = int(input("Enter N="))
    if N < 0:
        print("Ignore negative values")
        continue
    sum += N
    print(f"sum={sum}")
    if sum > 10:
        break

Enter N=5
sum=5
Enter N=-1
Ignore negative values
Enter N=0
sum=5
Enter N=4
sum=9
Enter N=20
sum=29


Often we need to leave a loop from the middle point of a body. Let us improve the example from the previous section. Not duplicated inputs anymore.

In [1]:
while True:
    s = input("Enter a word (blank to quit)")
    if s == "":
        break
    
    N = 3
    print(f"Now I repeat it {N} times: ", end="")
    for i in range(N):
        print(f"{s} ", end="")  # do not go to new line
    print()  # now go to new line when for-loop is finished

Enter a word (blank to quit)work
Now I repeat it 3 times: work work work 
Enter a word (blank to quit)


### Exercises

All exercises in this section are taken from book \[1\]

1\. Write a program that reads an integer from the user. Then your program should display a message indicating whether the integer is even or odd.

2\. It is commonly said that one human year is equivalent to 7 dog years. However this simple conversion fails to recognize that dogs reach adulthood in approximately two years. As a result, some people believe that it is better to count each of the first two human years as 10.5 dog years, and then count each additional human year as 4 dog years.

Write a program that implements the conversion from human years to dog years
described in the previous paragraph. Ensure that your program works correctly for conversions of less than two human years and for conversions of two or more human years. Your program should display an appropriate error message if the user enters a negative number.

3\. In this exercise you will create a program that reads a letter of the alphabet from the user. If the user enters **a**, **e**, **i**, **o** or **u** then your program should display a message indicating that the entered letter is a vowel. If the user enters **y** then your program should display a message indicating that sometimes **y** is a vowel, and sometimes **y** is a consonant. Otherwise your program should display a message indicating that the letter is a consonant.

4\. The following table lists the sound level in decibels for several common noises.

| Noise | Decibel Level |
| :-- | :-- |
| Jackhammer | 130 dB |
| Gas Lawnmower | 106 dB |
| Alarm Clock | 70 dB |
| Quite Room | 40 dB |

Write a program that reads a sound level in decibels from the user. If the user enters a decibel level that matches one of the noises in the table then your program should display a message containing only that noise. If the user enters a number of decibels between the noises listed then your program should display a message indicating which noises the value is between. Ensure that your program also generates reasonable output for a value smaller than the quietest noise in the table, and for a value larger than the loudest noise in the table.

5\. The year is divided into four seasons: spring, summer, fall (or autumn) and winter. While the exact dates that the seasons change vary a little bit from year to year because of the way that the calendar is constructed, we will use the following dates for this exercise:

| Season | First Day |
| :-- | :-- |
| Spring | March 20 |
| Summer | June 21 |
| Fall | September 22 |
| Winter | December 21 |

Create a program that reads a month and day from the user. The user will
enter the name of the month as a string, followed by the day within the month as an integer. Then your program should display the season associated with the date that was entered.

6\. The Chinese zodiac assigns animals to years in a 12 year cycle. One 12 year cycle is shown in the table below. The pattern repeats from there, with 2012 being another year of the dragon, and 1999 being another year of the hare.

| Year | Animal |
| :-- | :-- |
| 2000 | Dragon
| 2001 | Snake
| 2002 | Horse
| 2003 | Sheep
| 2004 | Monkey
| 2005 | Rooster
| 2006 | Dog
| 2007 | Pig
| 2008 | Rat
| 2009 | Ox
| 2010 | Tiger
| 2011 | Hare

Write a program that reads a year from the user and displays the animal associated with that year. Your program should work correctly for any year greater than or equal to zero, not just the ones listed in the table.

7\. A roulette wheel has 38 spaces on it. Of these spaces, 18 are black, 18 are red, and two are green. The green spaces are numbered 0 and 00. The red spaces are numbered 1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30 32, 34 and 36. The remaining integers between 1 and 36 are used to number the black spaces. 

Many different bets can be placed in roulette. We will only consider the following subset of them in this exercise:

- Single number (1 to 36, 0, or 00)
- Red versus Black
- Odd versus Even (Note that 0 and 00 do not pay out for even)
- 1 to 18 versus 19 to 36

Write a program that simulates a spin of a roulette wheel by using Python’s
random number generator. Display the number that was selected and all of the bets that must be payed. For example, if 13 is selected then your program should display:

```
The  spin resulted in 13...
Pay 13
Pay Black
Pay Odd
Pay 1 to 18
```

If the simulation results in 0 or 00 then your program should display Pay 0
or Pay 00 without any further output.

8\. In this exercise you will create a program that computes the average of a collection of values entered by the user. The user will enter 0 as a sentinel value to indicate
that no further values will be provided. Your program should display an appropriate error message if the first value entered by the user is 0.

_Hint: Because the 0 marks the end of the input it should not be included in the average._

9\. Write a program that displays a temperature conversion table for degrees Celsius and degrees Fahrenheit. The table should include rows for all temperatures between 0 and 100 degrees Celsius that are multiples of 10 degrees Celsius. Include appropriate
headings on your columns. The formula for converting between degrees Celsius and degrees Fahrenheit is as follows
$$
T_F=T_C \times 9 / 5 + 32
$$

10\. A particular zoo determines the price of admission based on the age of the guest. Guests 2 years of age and less are admitted without charge. Children between 3 and 12 years of age cost \\$14.00. Seniors aged 65 years and over cost \\$18.00. Admission for all other guests is \\$23.00.

Create a program that begins by reading the ages of all of the guests in a group
from the user, with one age entered on each line. The user will enter a blank line to indicate that there are no more guests in the group. Then your program should display the admission cost for the group with an appropriate message. The cost should be displayed using two decimal places.

11\. The value of $\pi$ can be approximated by the following infinite series:
$$
\pi \approx 3
+ \frac{4}{2\times 3\times 4}
- \frac{4}{4\times 5\times 6}
+ \frac{4}{6\times 7\times 8}
- \frac{4}{8\times 9\times 10}
+ \frac{4}{10\times 11\times 12}
- \cdots
$$
Write a program that displays 15 approximations of $\pi$. The first approximation should make use of only the first term from the infinite series. Each additional approximation displayed by your program should include one more term in the series, making it a better approximation of $\pi$ than any of the approximations displayed previously.

12\. Fizz-Buzz is a game that is sometimes played by children to help them learn about
division. The players are commonly arranged in a circle so that the game can progress
from player to player continually. The starting player begins by saying one, and then play passes to the player to the left. Each subsequent player is responsible for the next integer in sequence before play passes to the following player. On a player’s turn they must either say their number or one of following substitutions:

- If the player’s number is divisible by 3 then the player says fizz instead of their number.
- If the player’s number is divisible by 5 then the player says buzz instead of their number.

A player must say both fizz and buzz for numbers that are divisible by both 3
and 5. Any player that fails to perform the correct substitution or hesitates before
answering is eliminated from the game. The last player remaining is the winner.
Write a program that displays the answers for the first 100 numbers in the Fizz-
Buzz game. Each answer should be displayed on its own line.

13\. Write a program that implements Newton’s method to compute and display the
square root of a number, x, entered by the user. The algorithm for Newton’s method
follows:
```
Read x from the user
Initialize guess to x/2
While guess is not good enough do
    Update guess to be the average 
    of guess and x/guess
```

When this algorithm completes, guess contains an approximation of the square
root of x. The quality of the approximation depends on how you define “good
enough”. In the author’s solution, guess was considered good enough when the
absolute value of the difference between guess∗guess and x was less than or equal
to $10^{−12}$.

14\. A string is a palindrome if it is identical forward and backward. For example “anna”, “civic”, “level” and “hannah” are all examples of palindromic words. Write a program that reads a string from the user and uses a loop to determine whether or not it is a
palindrome. Display the result, including a meaningful output message.

_Aibohphobia is the extreme or irrational fear of palindromes. This word was constructed by prepending the -phobia suffix with it’s reverse, resulting in a palindrome. Ailihphilia is the fondness for or love of palindromes. It was constructed in the same manner from the -philia suffix._

## Lesson 3

### User defined functions

Let us recall why we need functions:

- to avoid retyping
- to increase clarity

Programmers can define their own functions. Splitting a code into many functions is a good programming style.

```python
def my_function(x, y):
    <do_something>
    return z
```

Keyword `def` starts a function definition. It is followed by a function name. Rules and limitations for function names are the same as for variables. Then function parameters are listed in parentheses. This lined is ended by colon.

A function can have no parameters. Parentheses are nevertheless required.

The function body must have an indent. 

The resulting variable, say `z`, is returned via `return z` statement. A function can have multiple `return` statements.

Function can return nothing. In this case one can write `return` statement without a returning value. Or one can even omit `return`. The function will automatically when all body will be executed.

Variables defined in a function body are local and do not exist outside the function.

In [4]:
def my_round(x):
    # function that round floats 
    return int((x + 0.5) // 1)

x = 12.34
i = my_round(x)
print(f"x={x}, my_round={i}")
x = 12.54
i = my_round(x)
print(f"x={x}, my_round={i}")

x=12.34, my_round=12
x=12.54, my_round=13


In [6]:
import datetime as dt

def currently():
    # function without args
    today = dt.date.today()
    print("Today's date:", today)
    
currently()

Today's date: 2020-10-22


In [7]:
def largest(x, y):
    # function with multiple returns
    if x >= y:
        return x
    else:
        return y
    
x = 3.4
y = 5.6
z = largest(x, y)
print(f"x={x}, y={y}, largest={z}")

x=3.4, y=5.6, largest=5.6


### Classes

Classes provide a means of bundling data and functionality together. Creating a new class creates a new type of object, allowing new instances of that type to be made. Each class instance can have attributes attached to it for maintaining its state. Class instances can also have methods (defined by its class) for modifying its state.

Keyword `class` starts class definition.

In [2]:
class Employee:
    count = 0  # class attribute

    def __init__(self, name, salary):
        # Constructor
        print("Constructor is called")
        self.name = name  # instance attribute
        self.salary = salary  # instance attribute
        self.id = Employee.count # instance attribute
        Employee.count += 1
        
    def __del__(self):
        # Destructor
        print("Destructor is called")
        Employee.count -= 1
   
    def __str__(self):
        print("Making string representation of the object")
        return f"Name: {self.name}, Salary: {self.salary}, Id: {self.id}"
    
    def promotion(self, percent):
        # User defined class method
        self.salary *= 1 + percent / 100

There are special methods. Their names are predefined in Python and are surrounded by two underscores. Above those methods are `__init__`, `__del__`, and `__str__`.

Programmer defines his/her own methods similarly to ordinary functions. Parameter `self` is a reference to the object itself.

When class has been defined one can create class instances: `<class_name>(<parameters>)`. The object instance is assigned to a variable.

In [3]:
# Recruiting two persons
emp1 = Employee("Peter", 1000)
emp2 = Employee("Razvan", 3000)
print(emp1)
print(emp2)
print(f"Total count: {Employee.count}")

Constructor is called
Constructor is called
Making string representation of the object
Name: Peter, Salary: 1000, Id: 0
Making string representation of the object
Name: Razvan, Salary: 3000, Id: 1
Total count: 2


Calling methods and attributes: `<object_variable>.<method_or_attribute_name>` 

In [4]:
# Increase salary to the first person
print(emp1.salary)
emp1.promotion(10)
print(emp1.salary)
print(emp1)

1000
1100.0
Making string representation of the object
Name: Peter, Salary: 1100.0, Id: 0


In [5]:
# Dismiss the second one
del emp2
print(emp2)

Destructor is called


NameError: name 'emp2' is not defined

In [6]:
# Now there is only one person
print(f"Total count: {Employee.count}")

Total count: 1


In [7]:
# Employ two new persons
emp2 = Employee("Anna", 3000)
emp3 = Employee("Helga", 4500)
print(f"Total count: {Employee.count}")

Constructor is called
Constructor is called
Total count: 3


In [8]:
# Compute total payment to the employees 
sum = emp1.salary + emp2.salary + emp2.salary 
print(f"Total: {sum}")

Total: 7100.0


In [9]:
# Greetings to everyone
s = "Hi " + emp1.name + ", " + emp2.name + " and " + emp3.name + "!\n"
s += "Happy New Year!"
print(s)

Hi Peter, Anna and Helga!
Happy New Year!


In [10]:
# Clean all
del emp1
del emp2
del emp3
Employee.count = 0

Destructor is called
Destructor is called
Destructor is called


### Inheritance

New class can be created on the basis of another class. This is called inheritance.

Here is the copy of the class Employee, just for convenience.

In [11]:
class Employee:
    count = 0  # class attribute

    def __init__(self, name, salary):
        # Constructor
        self.name = name  # instance attribute
        self.salary = salary  # instance attribute
        self.id = Employee.count # instance attribute
        Employee.count += 1
        
    def __del__(self):
        # Destructor
        Employee.count -= 1
   
    def __str__(self):
        return f"Name: {self.name}, Salary: {self.salary}, Id: {self.id}"
    
    def promotion(self, percent):
        # User defined class method
        self.salary *= 1 + percent / 100

We are going to defined a new class `Intern` based on `Employee`. `Employee` is called parent class or superclass. 

When we inherit form the parent class we have access to its attribute and methods and can modify them and add some more attributes and methods.

In [12]:
class Intern(Employee):
    
    def __init__(self, name, salary, trial_period):
        super().__init__(name, salary)
        self.trial_period = trial_period
    
    def trial_period_salary(self):
        return 0.5 * self.salary 
    
    def __str__(self):
        s = super().__str__()
        a = self.trial_period_salary()
        return f"Intern {s}, TrialPeriod: {self.trial_period}, TrialPeriodSalary: {a}"

In [16]:
# One regular employee and one intern
emp1 = Employee("Elsa", 8000)
inn1 = Intern("John", 5000, 3)
print(emp1)
print(inn1)

Name: Elsa, Salary: 8000, Id: 0
Intern Name: John, Salary: 5000, Id: 1, TrialPeriod: 3, TrialPeriodSalary: 2500.0


In [17]:
del emp1
del inn1
Employee.count = 0

### Lists

All variables above held one value: integer, float, string and so on. But to process a large amount of data one needs a named container that holds several values. 

List is a sequence of values separated by commas and enclosed in square brackets. A list can be assigned to variable just like a simple value.

In [18]:
v = [1.2, 3.4, 7.8]
print(v)

[1.2, 3.4, 7.8]


A list can be empty. Empty list is needed when we are going to put values in there as the program executes.

In [19]:
v = []
print(v)

[]


Size of a list can be computed using function `len`.

In [20]:
v = [4.4, 5.5, 6.6, 7.7]
print(len(v))
v = []
print(len(v))

4
0


Elements of a list are numbered sequentially with integers, starting from 0. Each integer identifies a specific element in the list, and is referred to as the index for that element.

Elements are accessed by their indexes: One uses variable name followed by square brackets with the index inside. Elements can be read or updated in this way.

In [21]:
# Reading list elements
v = [1.2, 3.4, 7.8]
print(v[0])
print(v[1])
print(v[2])

1.2
3.4
7.8


In [24]:
# Updating elements
v = [1.2, 3.4, 7.8]
print(v)
v[0] = -12.3
print(v)

[1.2, 3.4, 7.8]
[-12.3, 3.4, 7.8]


Lists admit elements of arbitrary types. Types can be mixed within one list. Even list can be an element of a list.

In [25]:
v = [12, 0.34, "mixture", True, [1,2,3]]
print(f"Value: {v[0]:9}, Type: {type(v[0])}")
print(f"Value: {v[1]:9}, Type: {type(v[1])}")
print(f"Value: {v[2]:9}, Type: {type(v[2])}")
print(f"Value: {v[3]:9}, Type: {type(v[3])}")
print(f"Value: {v[4]}, Type: {type(v[4])}")

Value:        12, Type: <class 'int'>
Value:      0.34, Type: <class 'float'>
Value: mixture  , Type: <class 'str'>
Value:         1, Type: <class 'bool'>
Value: [1, 2, 3], Type: <class 'list'>


A list holding data of various types can be updated with arbitrary types.

In [26]:
v = [12, 0.34, "mixture", True]
print(v)
v[2] = -1
print(v)

[12, 0.34, 'mixture', True]
[12, 0.34, -1, True]


List with data of different types can be used to represent a table 

In [28]:
# name, salary, age, ages of children
tab = [
    ["Peter", 1000.12, 21, [2, 1]],
    ["Helga", 2500.79, 32, [4, 8, 1]],
    ["John", 1500.81, 24, [3, 2]]]

### Loops and lists

Containers like list are useful for data processing with loops. 

A loop `for` admits a list as a collection of values for the loop variable. 

In [74]:
# Compute average of list elements
sum = 0
cnt = 0
for x in [2.3, 3.4, 4.5, -1.2]:
    sum += x
    cnt += 1
    
avg = sum / cnt
print(f"avg={avg}")

avg=2.25


We can also run through a list using an index variable

In [75]:
lst = [2.3, 3.4, 4.5, -1.2]
sum = 0
cnt = 0
for i in range(len(lst)):
    sum += lst[i]
    cnt += 1
    
avg = sum / cnt
print(f"avg={avg}")

avg=2.25


This way of list processing is not so fast in Python. The previous one is better: that was Pythonic way.

But what if we need element indexes. Use `enumerate`.

In [40]:
# Using enumerate to get indexes together with elements
for i, x in enumerate([221.23, 432.1, 431.121, 82.2, 991.211]):
    print(f"i={i}, x={x}")

i=0, x=221.23
i=1, x=432.1
i=2, x=431.121
i=3, x=82.2
i=4, x=991.211


One can iterate over two or more lists

In [41]:
x_list = [11, 12, 13]
y_list = ["one", "two", "three"]
for x, y in zip(x_list, y_list):
    print(f"x={x}, y={y}")

x=11, y=one
x=12, y=two
x=13, y=three


Using a table (list of list)

In [34]:
tab = [
    ["Peter", 1000.12, 21, [2, 1]],
    ["Helga", 2500.79, 32, [4, 8, 1]],
    ["John", 1500.81, 24, [3, 2]]]

tot = 0
for emp in tab:
    print(f"emp now is equal to {emp}")
    s = emp[1]
    print(f"   take the salary, s={s}")
    itx = s * 0.13
    print(f"   compute income tax, itx={itx}")
    tot += itx
    print(f"   tot={tot}")
    
print(f"Total income tax {tot}")

emp now is equal to ['Peter', 1000.12, 21, [2, 1]]
   take the salary, s=1000.12
   compute income tax, itx=130.0156
   tot=130.0156
emp now is equal to ['Helga', 2500.79, 32, [4, 8, 1]]
   take the salary, s=2500.79
   compute income tax, itx=325.1027
   tot=455.11830000000003
emp now is equal to ['John', 1500.81, 24, [3, 2]]
   take the salary, s=1500.81
   compute income tax, itx=195.1053
   tot=650.2236
Total income tax 650.2236


A loop `while` can also be useful for lists processing.

An example: Assume we have 8 cities connected by roads. Connected cities are encoded in list `road`: element `road[i]` contains a city number `j` that is connected with the city `i`. The program must find a path starting from city `n1` to city `n2`.

In [48]:
n1 = int(input("Start city n1="))
n2 = int(input("Fnish city n2="))

road = [4, 1, 3, 7, 6, 0, 2, 5]
STEPS_MAX = 10

i = n1
cnt = 0
while True:
    print(f"  go from city {i} to city {road[i]}")
    i = road[i]
    if i == n2:
        print("finish")
        break
    cnt += 1
    if cnt > STEPS_MAX:
        print(f"path not found after {cnt} steps")
        break
    

Start city n1=0
Fnish city n2=4
  go from city 0 to city 4
finish


### Manipulations with lists

List can grow and shrink, new elements can be inserted, an element can be deleted. 

Lists are considered as objects, i.e., instances of the class "list". Most of the manipulations with lists are performed using methods.

In [49]:
# Add an element to the end of a list
x = [1, 2, 3, 4]
x.append(99)
print(x)

[1, 2, 3, 4, 99]


In [50]:
# Insert an element in arbitary location
x = [10, 9, 8, 7]
x.insert(2, 99)
print(x)

[10, 9, 99, 8, 7]


In [51]:
# Remove last element and store it in a variable
x = [1, 2, 3, 4, 5]
a = x.pop()
print(x)
print(a)

[1, 2, 3, 4]
5


In [52]:
# Remove an element at a specific position
x = [1, 2, 3, 4, 5]
a = x.pop(3)
print(x)
print(a)

[1, 2, 3, 5]
4


In [55]:
# Remove an element by value
x = [3.2, 4.3, 5.121, 4.3]
x.remove(5.121)
print(x)

[3.2, 4.3, 4.3]


In [60]:
# Reverse the order of elements
x = [1, 2, 3, 4, 5]
x.reverse()
print(x)

[5, 4, 3, 2, 1]


In [63]:
# Sort a list
x = [54, -1, 99, 21, -11]
x.sort()
print(x)

[-11, -1, 21, 54, 99]


In [74]:
# Also sort a list, but creates a new copy
x = [54, -1, 99, 21, -11]
y = sorted(x)
print(x)
print(y)

[54, -1, 99, 21, -11]
[-11, -1, 21, 54, 99]


In [64]:
# Determine whether or not a value is present in a list
x = [4.3,  55.4, 6.2, 4.3]
print(4.3 in x)
print(4.4 in x)

True
False


In [69]:
# Find the position of an element
x = [4.3,  55.4, 6.2, 4.3]
print(x.index(55.4))
print(x.index(55.5))

1


ValueError: 55.5 is not in list

In [78]:
# Collecting values in a list
data = []
while True:
    s = input("Enter a value (blank to quit) ")
    if s == "":
        break
    data.append(float(s))
    
print(data)

Enter a value (blank to quit) 1
Enter a value (blank to quit) 2
Enter a value (blank to quit) 3
Enter a value (blank to quit) 
[1.0, 2.0, 3.0]


### Dictionaries

List is an enumerated collection of values. To read or update an element we must know its index.

Dictionary is a collection of named values. Each element is pair key-value. Key is a name of the value.

In [80]:
# Dictionary defentioon. Observe curly brackets and colons
emp = {"Helga": 1995, "John": 1992, "Igor": 1999}

# Add a value
emp["July"] = 1990

# Acces to elements by their names (keys)
print(emp["Helga"])
print(emp["Igor"])
print(emp["July"])

1995
1999
1990


In [82]:
# Values can be updated
d = {}
d["first_counter"] = 1
d["second_counter"] = 100

d["first_counter"] += 1
d["second_counter"] += 100

print(d["first_counter"], d["second_counter"])

2 200


In [84]:
# Remove an element. Romoved value is returned
emp = {"Helga": 1995, "John": 1992, "Igor": 1999}
x = emp.pop("Igor")
print(x)

1999


In [86]:
# Iteration over keys
emp = {"Helga": 1995, "John": 1992, "Igor": 1999, "July": 1990}

for x in emp:
    print(x, emp[x])

Helga 1995
John 1992
Igor 1999
July 1990


In [87]:
# Iteration over values
emp = {"Helga": 1995, "John": 1992, "Igor": 1999, "July": 1990}

for x in emp.values():
    print(x)

1995
1992
1999
1990


### Exceptions

When an error occurs program stops. There is a way to handle it: when it happens execution jumps to a specific area of code to precess an error. This mechanism is called exceptions.

```python
try:
    <some_code_where_error_can_occur>
except <error_name>:
    <do_something_to_process_error>
except <another_error_name>:
    <process_another_error>
```

Consider a program with an error:

In [69]:
# Program stops when zero is encountered
div = [1.1, 2.1, 0.0, 3.2]
for d in div:
    x = 10 / d;
    print(f"10 / {d} = {x}")

10 / 1.1 = 9.09090909090909
10 / 2.1 = 4.761904761904762


ZeroDivisionError: float division by zero

Find the error name: `ZeroDivisionError`. Use it to create exception handler.

In [60]:
# Now program runs to the end
div = [1.1, 2.1, 0.0, 3.2]
for d in div:
    try:
        x = 10 / d;
    except ZeroDivisionError:
        x = float("inf")
    print(f"10 / {d} = {x}")

10 / 1.1 = 9.09090909090909
10 / 2.1 = 4.761904761904762
10 / 0.0 = inf
10 / 3.2 = 3.125


### Files

Results of computations are saved to files. Before using a file must be opened with function `open()`. It has two parameters: file name and mode. Mode can be reading and writing (and some others). This function returns an object representing the file. 

- Writing data: mode='w', method `.write()`
- Reading data: mode='r', method `.read()`

After using a file it needs to be closed with the method `.close()`. Otherwise some data may be lost.

Writing a file one must remember to end lines at appropriate positions. Symbol is `\n` is used for it.

In [67]:
# Create the simplest file
fn = "my_file1.txt"
fdat = open(fn, "w")
fdat.write("O tempora!\nO mores!\n")
fdat.close()

In [68]:
# Download the file from Colab or just go to it
try:
    from google.colab import files
    files.download(fn)
except ModuleNotFoundError:
    import os
    print(f"You are not in Colab. Just locate your file at\n{os.path.join(os.getcwd(), fn)}")

You are not in Colab. Just locate your file at
/home/pavel/MEGA/hse/data-sc-intro/my_file1.txt


In [27]:
# Beter way of working with files: never forget to close it
fn = "my_file2.txt"
with open(fn, 'w') as fdat:
    fdat.write("Veni,\nvidi,\nvici\n")

In [28]:
# Download the file from Colab or just go to it
try:
    from google.colab import files
    files.download(fn)
except ModuleNotFoundError:    
    import os
    print(f"You are not in Colab. Just locate your file at\n{os.path.join(os.getcwd(), fn)}")

You are not in Colab. Just locate your file at
/home/pavel/MEGA/hse/data-sc-intro/my_file2.txt


In [30]:
# Write a file in a loop
fn = "my_file3.txt"
with open(fn, 'w') as fdat:
    for i in range(10):
        fdat.write(f"i = {i}, 2**i = {2**i}\n")

In [28]:
# Download the file from Colab or just go to it
try:
    from google.colab import files
    files.download(fn)
except ModuleNotFoundError:    
    import os
    print(f"You are not in Colab. Just locate your file at\n{os.path.join(os.getcwd(), fn)}")

You are not in Colab. Just locate your file at
/home/pavel/MEGA/hse/data-sc-intro/my_file2.txt


In [37]:
# Example of reading file. First write it
fn = "my_file4.txt"
txt = \
"""When, in disgrace with fortune and men's eyes,
I all alone beweep my outcast state,
And trouble deaf heaven with my bootless cries,
And look upon myself, and curse my fate,
Wishing me like to one more rich in hope,
Featured like him, like him with friends possessed,
Desiring this man's art and that man's scope,
With what I most enjoy contented least;
Yet in these thoughts myself almost despising,
Haply I think on thee - and then my state,
Like to the lark at break of day arising
From sullen earth, sings hymns at heaven's gate;
For thy sweet love rememb'red such wealth brings
That then I scorn to change my state with kings."""
with open(fn, "w") as fdat:
    fdat.write(txt)

In [38]:
# Read it all at once
fn = "my_file4.txt"
with open(fn, "r") as fdat:
    s = fdat.read()
    
print(s)

When, in disgrace with fortune and men's eyes,
I all alone beweep my outcast state,
And trouble deaf heaven with my bootless cries,
And look upon myself, and curse my fate,
Wishing me like to one more rich in hope,
Featured like him, like him with friends possessed,
Desiring this man's art and that man's scope,
With what I most enjoy contented least;
Yet in these thoughts myself almost despising,
Haply I think on thee - and then my state,
Like to the lark at break of day arising
From sullen earth, sings hymns at heaven's gate;
For thy sweet love rememb'red such wealth brings
That then I scorn to change my state with kings.


If a file is large it is better to read it line by line. We enumerate lines using `enumerate`.

In [49]:
# Here we enumerate lines, compute lengths and print first 10 symbols
fn = "my_file4.txt"
CUT = 10
with open(fn, "r") as fdat:
    for i, line in enumerate(fdat):
        n = len(line)
        s = line[:CUT]
        print(f"{i+1:3}: {s}..., len={n}")

  1: When, in d..., len=47
  2: I all alon..., len=37
  3: And troubl..., len=48
  4: And look u..., len=41
  5: Wishing me..., len=42
  6: Featured l..., len=52
  7: Desiring t..., len=46
  8: With what ..., len=40
  9: Yet in the..., len=47
 10: Haply I th..., len=43
 11: Like to th..., len=41
 12: From sulle..., len=49
 13: For thy sw..., len=49
 14: That then ..., len=48


In [56]:
# Here we compute number of 'a' in each line
fn = "my_file4.txt"
SYMB = "a"
tot = 0
with open(fn, "r") as fdat:
    for i, line in enumerate(fdat):
        cnt = 0
        for s in line:
            if s == SYMB:
                cnt += 1
            
        tot += cnt
        print(f"Number of '{SYMB}' in line {i:3} is {cnt:3}")

print(f"Total number of '{SYMB}' is {tot}")

Number of 'a' in line   0 is   2
Number of 'a' in line   1 is   4
Number of 'a' in line   2 is   2
Number of 'a' in line   3 is   2
Number of 'a' in line   4 is   0
Number of 'a' in line   5 is   1
Number of 'a' in line   6 is   5
Number of 'a' in line   7 is   2
Number of 'a' in line   8 is   1
Number of 'a' in line   9 is   3
Number of 'a' in line  10 is   5
Number of 'a' in line  11 is   4
Number of 'a' in line  12 is   1
Number of 'a' in line  13 is   3
Total number of 'a' is 35


### Exercises

All exercises in this section, except 4 and 5, are taken from book \[1\]

1\. In a particular jurisdiction, taxi fares consist of a base fare of \\$4.00, plus \\$0.25 for every 140 meters traveled. Write a function that takes the distance traveled (in kilometers) as its only parameter and returns the total fare as its only result. Write a main program that demonstrates the function. 

_Hint: Taxi fares change over time. Use constants to represent the base fare and the variable portion of the fare so that the program can be updated easily when the rates increase._

2\. Words like first, second and third are referred to as ordinal numbers. In this exercise, you will write a function that takes an integer as its only parameter and returns a string containing the appropriate English ordinal number as its only result. Your function must handle the integers between 1 and 12 (inclusive). It should return an
empty string if the function is called with an argument outside of this range. Include
a main program that demonstrates your function by displaying each integer from 1 to 12 and its ordinal number.

3\. Many people do not use capital letters correctly, especially when typing on small
devices like smart phones. To help address this situation, you will create a function
that takes a string as its only parameter and returns a new copy of the string that has
been correctly capitalized. In particular, your function must:

- Capitalize the first non-space character in the string,
- Capitalize the first non-space character after a period, exclamation mark or question mark, and
- Capitalize a lowercase "i" if it is preceded by a space and followed by a space, period, exclamation mark, question mark or apostrophe.

Implementing these transformations will correct most capitalization errors. For example, if the function is provided with the string "what time do i have to be there? what’s the address? this time i’ll try to be on time!" then it should return the string
"What time do I have to be there? What’s the address? This time I’ll try to be on time!". Include a main program that reads a string from the user, capitalizes it using your function, and displays the result.


4\. Create a class that checks the authorization. Its constructor takes correct user name and password and store them as attributes. To increase security the password must not be stored as it is. It must be converted to its hash using function `hash()`.

The class has a method `check` that accepts a user name and password inputed by a user and return `True` if they are correct and `False` otherwise. 

Write a program that demonstrates how this class works.

5\. Passwords are never stored in their original form. A random string of symbols is added to each password and then hashed. The added string is called "salt". 

Create a class whose constructor accepts and stores a salt string, and also it has a method `marinate()` that takes a password and return hash of the salted password. Compute hash using function `hash()`.

6\. When analyzing data collected as part of a science experiment it may be desirable
to remove the most extreme values before performing other calculations. Write a function that takes a list of values and an non-negative integer, n, as its parameters. The function should create a new copy of the list with the n largest elements and the
n smallest elements removed. Then it should return the new copy of the list as the function's only result. The order of the elements in the returned list does not have to match the order of the elements in the original list.

Write a main program that demonstrates your function. It should read a list of
numbers from the user and remove the two largest and two smallest values from it by
calling the function described previously. Display the list with the outliers removed,
followed by the original list. Your program should generate an appropriate error
message if the user enters less than 4 values.

7\. Create a program that reads integers from the user until a blank line is entered. Once
all of the integers have been read your program should display all of the negative numbers, followed by all of the zeros, followed by all of the positive numbers. Within each group the numbers should be displayed in the same order that they were entered by the user. For example, if the user enters the values 3, -4, 1, 0, -1, 0, and -2 then your program should output the values -4, -1, -2, 0, 0, 3, and 1. Your program should display each value on its own line.


8\. Pig Latin is a language constructed by transforming English words. While the origins of the language are unknown, it is mentioned in at least two documents from the nineteenth century, suggesting that it has existed for more than 100 years. The following rules are used to translate English into Pig Latin:

- If the word begins with a consonant (including y), then all letters at the beginning of the word, up to the first vowel (excluding y), are removed and then added to the end of the word, followed by ay. For example, computer becomes omputercay and think becomes inkthay. 
- If the word begins with a vowel (not including y), then way is added to the end of the word. For example, algorithm becomes algorithmway and office becomes officeway. 

Write a program that reads a line of text from the user. Then your program should
translate the line into Pig Latin and display the result. You may assume that the string
entered by the user only contains lowercase letters and spaces.


9\. Create a program that determines and displays the number of unique characters in a string entered by the user. For example, "Hello, World!" has 10 unique characters while "zzz" has only one unique character. Use a dictionary or set to solve this problem.


10\. While the popularity of cheques as a payment method has diminished in recent years, some companies still issue them to pay employees or vendors. The amount being paid normally appears on a cheque twice, with one occurrence written using digits, and the other occurrence written using English words. Repeating the amount in two
different forms makes it much more difficult for an unscrupulous employee or vendor to modify the amount on the cheque before depositing it.

In this exercise, your task is to create a function that takes an integer between 0 and 999 as its only parameter, and returns a string containing the English words for that number. For example, if the parameter to the function is 142 then your function should return "one hundred forty two". Use one or more dictionaries to implement your solution rather than large if/elif/else constructs. Include a main program that reads an integer from the user and displays its value in English words.
